### ISSUE TITLE
Amazing design  but can not grt anyone to make them

### ISSUE THREAD

**Issue by DecanFrost** [Element18592/360-Slim-PLL-QSB#3]
I have tried several sites to make these and they tell me I need to enlarge the width by 5mm all around

**Comment by ShawMerlin** [comment]
If you are in the US, try OshPark, they printed a bunch for me without issue.

**Comment by Element18592** [comment]
This isn't an issue with the board itself but instead with the manufacturers limitation on their design rules. Unfortunately due to the limited area we're working with on slims, these PCBs require strict design rules. Places like JLC will give you a hard time but if you're persistent they will manufacture them. Also as per @ShawMerlin they should work fine with OSHPark as well granted their minimum thickness is .8mm however it should still work out fine.
